# Generated by Django 3.2.4 on 2021-06-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('custom_number', models.IntegerField(verbose_name='Customer Number')),
                ('shirt', models.IntegerField(blank=True, null=True, verbose_name='T-Shirt')),
                ('trouser', models.IntegerField(blank=True, null=True, verbose_name='Trouser/Short')),
                ('underwear', models.IntegerField(blank=True, null=True, verbose_name='Single/Boxers')),
                ('native', models.IntegerField(blank=True, null=True, verbose_name='Complete Native')),
                ('duvet', models.IntegerField(blank=True, null=True, verbose_name='Duvet')),
                ('duver_beddings', models.IntegerField(blank=True, null=True, verbose_name='Duvet and Beddings')),
                ('towel', models.IntegerField(blank=True, null=True, verbose_name='Towel')),
                ('dropp_off', models.DateTimeField(auto_now=True, null=True)),
                ('commission', models.CharField(blank=True, max_length=200, null=True, verbose_name='Refered Byss')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField(verbose_name='Date Of Birth')),
                ('reason_for_registering', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(verbose_name='Registration Date')),
                ('exp_date', models.DateTimeField(verbose_name='Expiring Date')),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes')),
                ('refered_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='TicketNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=120)),
                ('expired', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user1.members')),
            ],
            options={
                'verbose_name': 'Ticket Number ',
            },
        ),
        migrations.AddField(
            model_name='members',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user1.package'),
        ),
    ]
